FROM alpine

ARG USERNAME=sandbox
ARG PASSWORD=changeme

# install openssh
RUN apk add openssh
COPY sshd_config /etc/ssh/sshd_config
RUN /usr/bin/ssh-keygen -A

# add secure user
RUN adduser -s /bin/sh --disabled-password -H $USERNAME
RUN echo $USERNAME:$PASSWORD > /root/pass.txt \
  && chpasswd < /root/pass.txt \
  && rm /root/pass.txt

# run ssh in foreground
CMD /usr/sbin/sshd -D
